apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: monitoring
  name: noderesource-alerts-rule
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: kubernetes-alerts
    rules:
      # Node down
      - alert: NodeDown
        expr: up{job="kubelet"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Node {{ $labels.instance }} is down in cluster {{ $externalLabels.cluster }}"
          description: "Prometheus could not scrape {{ $labels.job }} on {{ $labels.instance }} for 2 minutes."

      # High CPU usage
      - alert: HighNodeCPU
        expr: 100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on node {{ $labels.instance }} in cluster {{ $externalLabels.cluster }}"
          description: "Node is using > 90% CPU for the last 5 minutes."

      # High memory usage
      - alert: HighNodeMemory
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on node {{ $labels.instance }} in cluster {{ $externalLabels.cluster }}"
          description: "Memory usage is > 90% on node {{ $labels.instance }}."

      # Disk space usage
      - alert: NodeDiskAlmostFull
        expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Disk almost full on {{ $externalLabels.instance }} in cluster {{ $externalLabels.cluster }}"
          description: "Disk space is > 90% used on {{ $labels.instance }}."
          
      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready", status="true"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Node not ready: {{ $labels.node }}  in cluster {{ $externalLabels.cluster }"
          description: "Node {{ $labels.node }} is not in Ready state."
        #  Node Disk Pressure
        - alert: NodeDiskPressure
          expr: kube_node_status_condition{condition="DiskPressure", status="true"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Node disk pressure: {{ $labels.node }} on cluster {{ $externalLabels.cluster }}"
            description: "Node {{ $labels.node }} is experiencing disk pressure for more than 5 minutes."
        #  Node Memory Pressure
        - alert: NodeMemoryPressure
          expr: kube_node_status_condition{condition="MemoryPressure", status="true"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Node memory pressure: {{ $labels.node }} on cluster {{ $externalLabels.cluster }}"
            description: "Node {{ $labels.node }} is experiencing memory pressure for more than 5 minutes."
        #  Node Network Unavailable
        - alert: NodeNetworkUnavailable
          expr: kube_node_status_condition{condition="NetworkUnavailable", status="true"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Node network unavailable: {{ $labels.node }} on cluster {{ $externalLabels.cluster }}"
            description: "Node {{ $labels.node }} has network unavailable condition for more than 5 minutes."

