apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: monitoring
  name: test-email-alert
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: test
    rules:
    - alert: TestEmailAlert
      expr: vector(1)
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "This is a test alert"
        description: "If you're seeing this, email alerts are working."
