apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: monitoring
  name: workloads-alerts-rule
  labels:
    release: prometheus-stack
spec:
  groups:
    - name: kubernetes-monitoring-alerts
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0.3
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Pod crash looping: {{ $labels.pod }} in {{ $labels.namespace }} on cluster {{ $externalLabels.cluster }}"
            description: "Pod {{ $labels.pod }} is restarting frequently."

        - alert: PodPendingTooLong
          expr: kube_pod_status_phase{phase="Pending"} > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod stuck in Pending: {{ $labels.pod }} on cluster {{ $externalLabels.cluster }}"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is Pending for over 5 minutes."

        - alert: ContainerOOMKilled
          expr: kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} == 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "OOM killed: {{ $labels.container }} in {{ $labels.pod }} on cluster {{ $externalLabels.cluster }}"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} was OOMKilled."

        - alert: DeploymentReplicasUnavailable
          expr: kube_deployment_status_replicas_unavailable > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Deployment unavailable: {{ $labels.deployment }} on cluster {{ $externalLabels.cluster }}"
            description: "Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has unavailable replicas."

        - alert: StatefulSetReplicasMismatch
          expr: kube_statefulset_status_replicas_ready != kube_statefulset_status_replicas
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "StatefulSet replica mismatch: {{ $labels.statefulset }} on cluster {{ $externalLabels.cluster }}"
            description: "StatefulSet {{ $labels.statefulset }} in namespace {{ $labels.namespace }} does not have all replicas ready."

        #  StatefulSet Pods Not Ready
        - alert: StatefulSetPodsNotReady
          expr: (kube_statefulset_status_replicas_ready < kube_statefulset_spec_replicas)
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "StatefulSet not fully ready: {{ $labels.statefulset }} on cluster {{ $externalLabels.cluster }}"
            description: "StatefulSet {{ $labels.statefulset }} in namespace {{ $labels.namespace }} has pods not in ready state."

        - alert: DaemonSetPodsMisscheduled
          expr: kube_daemonset_status_number_misscheduled > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Misscheduled DaemonSet pods: {{ $labels.daemonset }} on cluster {{ $externalLabels.cluster }}"
            description: "DaemonSet {{ $labels.daemonset }} in namespace {{ $labels.namespace }} has misscheduled pods."

        # DaemonSet Not All Pods Ready
        - alert: DaemonSetNotAllPodsReady
          expr: kube_daemonset_status_number_ready < kube_daemonset_status_desired_number_scheduled
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "DaemonSet not ready: {{ $labels.daemonset }} on cluster {{ $externalLabels.cluster }}"
            description: "Not all DaemonSet pods are ready for {{ $labels.daemonset }} in namespace {{ $labels.namespace }}."
