apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-msteams
  namespace: monitoring
  labels:
    app: prometheus-msteams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-msteams
  template:
    metadata:
      labels:
        app: prometheus-msteams
    spec:
      containers:
      - name: prometheus-msteams
        image: bzon/prometheus-msteams
        args:
          - "-config-file"
          - "/etc/config/connectors.yaml"
        ports:
        - containerPort: 2000
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: msteams-config
